<a href="https://colab.research.google.com/github/sreejas7919-bit/DSA_6/blob/main/Case_Study_on_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ***Case Study on Preprocessing***

Dataset Overview
Load the dataset House_Pricing.csv
Display basic information about the dataset using .info() and .describe() to understand the features, data types, and any initial insights into missing values.

In [44]:
#Import Libraries
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split


#pandas → Dataset load ചെയ്യാനും DataFrame operations ചെയ്യാനും ഉപയോഗിക്കുന്നു.
#numpy → Numerical calculations ചെയ്യാൻ ഉപയോഗിക്കുന്നു.
#SimpleImputer → Missing values fill ചെയ്യാൻ.
#MinMaxScaler → Numerical features scale ചെയ്യാൻ.
#train_test_split → Dataset training, testing ആയി split ചെയ്യാൻ.

In [45]:
#load dataset
df = pd.read_csv("House_Pricing.csv")

In [46]:
df.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         21613 non-null  int64
 1   Date House was Sold                        21613 non-null  object
 2   Sale Price                                 21609 non-null  float64
 3   No of Bedrooms                             21613 non-null  int64
 4   No of Bathrooms                            21609 non-null  float64
 5   Flat Area (in Sqft)                        21604 non-null  float64
 6   Lot Area (in Sqft)                         21604 non-null  float64
 7   No of Floors                               21613 non-null  float64
 8   Waterfront View                            21613 non-null  object
 9   No of Times Visited                        2124 non-null   object
 10  Condition of the House                     21613 non-null  object
 11  Overall Grade                              21613 non-null  int64
 12  Area of the House from Basement (in Sqft)  21610 non-null  float64
 13  Basement Area (in Sqft)                    21613 non-null  int64
 14  Age of House (in Years)                    21613 non-null  int64
 15  Renovated Year                             21613 non-null  int64
 16  Zipcode                                    21612 non-null  float64
 17  Latitude                                   21612 non-null  float64
 18  Longitude                                  21612 non-null  float64
 19  Living Area after Renovation (in Sqft)     21612 non-null  float64
 20  Lot Area after Renovation (in Sqft)        21613 non-null  int64
dtypes: float64(10), int64(7), object(4)
memory usage: 3.5+ MB

In [48]:
df.describe()

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
count,2.161300e+04,2.160900e+04,21613.000000,21609.000000,21604.000000,2.160400e+04,21613.000000,21613.000000,21610.000000,21613.000000,21613.000000,21613.000000,21612.000000,21612.000000,21612.000000,21612.000000,21613.000000
mean,4.580302e+09,5.401984e+05,3.370842,2.114732,2079.931772,1.510776e+04,1.494309,7.623467,1788.344193,291.509045,46.994864,84.402258,98077.937766,47.560048,-122.213892,1986.538914,12768.455652
std,2.876566e+09,3.673890e+05,0.930062,0.770138,918.487597,4.142827e+04,0.539989,1.105439,827.982604,442.575043,29.373411,401.679240,53.505425,0.138565,0.140830,685.404255,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,1.000000,290.000000,0.000000,3.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1429.250000,5.040000e+03,1.000000,7.000000,1190.000000,0.000000,21.000000,0.000000,98033.000000,47.470975,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.617500e+03,1.500000,7.000000,1560.000000,0.000000,43.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068825e+04,2.000000,8.000000,2210.000000,560.000000,67.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,10.000000,9410.000000,4820.000000,118.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [49]:
#Missing Values
df.isnull().sum()

ID                                               0
Date House was Sold                              0
Sale Price                                       4
No of Bedrooms                                   0
No of Bathrooms                                  4
Flat Area (in Sqft)                              9
Lot Area (in Sqft)                               9
No of Floors                                     0
Waterfront View                                  0
No of Times Visited                          19489
Condition of the House                           0
Overall Grade                                    0
Area of the House from Basement (in Sqft)        3
Basement Area (in Sqft)                          0
Age of House (in Years)                          0
Renovated Year                                   0
Zipcode                                          1
Latitude                                         1
Longitude                                        1
Living Area after Renovation (in Sqft)           1
Lot Area after Renovation (in Sqft)              0
dtype: int64

Duplicate Removal
Rows: Check for duplicate rows in the dataset, if any, and remove them.
Columns: Identify and drop duplicate columns, if any, based on their values.

In [50]:
#Duplicate Rows Count
df.duplicated().sum()

np.int64(0)

In [51]:
#Remove Duplicate Rows
df = df.drop_duplicates()

In [52]:
#Duplicate Rows Count
df.duplicated().sum()

np.int64(0)

In [53]:
#Remove Duplicate Columns
df = df.loc[:, ~df.T.duplicated()]

In [54]:
print(df.T.duplicated().sum())

0

Handling Missing Values
Identify missing values in each column.
Handle missing values:
For numerical columns, use imputation techniques like mean/median imputation.
For categorical columns, fill with mode.
Document your approach for each feature with missing data.

In [55]:
#Handling Missing Values
#Numerical Columns
num_cols = df.select_dtypes(include=['int64','float64']).columns
df[num_cols]

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,221900.0,3,1.00,1180.0,5650.0,1.0,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,538000.0,3,2.25,2570.0,7242.0,2.0,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,180000.0,2,1.00,770.0,10000.0,1.0,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,604000.0,4,3.00,1960.0,5000.0,1.0,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,510000.0,3,2.00,1680.0,8080.0,1.0,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,360000.0,3,2.50,1530.0,1131.0,3.0,8,1530.0,0,9,0,98103.0,47.6993,-122.346,1530.0,1509
21609,6600060120,400000.0,4,2.50,2310.0,5813.0,2.0,8,2310.0,0,4,0,98146.0,47.5107,-122.362,1830.0,7200
21610,1523300141,402101.0,2,0.75,1020.0,1350.0,2.0,7,1020.0,0,9,0,98144.0,47.5944,-122.299,1020.0,2007
21611,291310100,400000.0,3,2.50,1600.0,2388.0,2.0,8,1600.0,0,14,0,98027.0,47.5345,-122.069,1410.0,1287
21612,1523300157,325000.0,2,0.75,1020.0,1076.0,2.0,7,1020.0,0,10,0,98144.0,47.5941,-122.299,1020.0,1357

In [56]:
#Categorical Columns
cat_cols = df.select_dtypes(include=['object']).columns
df[cat_cols]

,Date House was Sold,Waterfront View,No of Times Visited,Condition of the House
0,14 October 2017,No,NaN,Fair
1,14 December 2017,No,NaN,Fair
2,15 February 2016,No,NaN,Fair
3,14 December 2017,No,NaN,Excellent
4,15 February 2016,No,NaN,Fair
...,...,...,...,...
21608,14 May 2017,No,NaN,Fair
21609,15 February 2016,No,NaN,Fair
21610,14 June 2017,No,NaN,Fair
21611,15 January 2016,No,NaN,Fair
21612,14 October 2017,No,NaN,Fair

In [57]:
#Mean Imputation
num_imputer = SimpleImputer(strategy='mean')
df[num_cols] = num_imputer.fit_transform(df[num_cols])
df[num_cols]

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7.129301e+09,221900.0,3.0,1.00,1180.0,5650.0,1.0,7.0,1180.0,0.0,63.0,0.0,98178.0,47.5112,-122.257,1340.0,5650.0
1,6.414100e+09,538000.0,3.0,2.25,2570.0,7242.0,2.0,7.0,2170.0,400.0,67.0,1991.0,98125.0,47.7210,-122.319,1690.0,7639.0
2,5.631500e+09,180000.0,2.0,1.00,770.0,10000.0,1.0,6.0,770.0,0.0,85.0,0.0,98028.0,47.7379,-122.233,2720.0,8062.0
3,2.487201e+09,604000.0,4.0,3.00,1960.0,5000.0,1.0,7.0,1050.0,910.0,53.0,0.0,98136.0,47.5208,-122.393,1360.0,5000.0
4,1.954401e+09,510000.0,3.0,2.00,1680.0,8080.0,1.0,8.0,1680.0,0.0,31.0,0.0,98074.0,47.6168,-122.045,1800.0,7503.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,2.630000e+08,360000.0,3.0,2.50,1530.0,1131.0,3.0,8.0,1530.0,0.0,9.0,0.0,98103.0,47.6993,-122.346,1530.0,1509.0
21609,6.600060e+09,400000.0,4.0,2.50,2310.0,5813.0,2.0,8.0,2310.0,0.0,4.0,0.0,98146.0,47.5107,-122.362,1830.0,7200.0
21610,1.523300e+09,402101.0,2.0,0.75,1020.0,1350.0,2.0,7.0,1020.0,0.0,9.0,0.0,98144.0,47.5944,-122.299,1020.0,2007.0
21611,2.913101e+08,400000.0,3.0,2.50,1600.0,2388.0,2.0,8.0,1600.0,0.0,14.0,0.0,98027.0,47.5345,-122.069,1410.0,1287.0
21612,1.523300e+09,325000.0,2.0,0.75,1020.0,1076.0,2.0,7.0,1020.0,0.0,10.0,0.0,98144.0,47.5941,-122.299,1020.0,1357.0

In [58]:
#Mode Imputation
cat_imputer = SimpleImputer(strategy='most_frequent')
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])
df[cat_cols]

,Date House was Sold,Waterfront View,No of Times Visited,Condition of the House
0,14 October 2017,No,Twice,Fair
1,14 December 2017,No,Twice,Fair
2,15 February 2016,No,Twice,Fair
3,14 December 2017,No,Twice,Excellent
4,15 February 2016,No,Twice,Fair
...,...,...,...,...
21608,14 May 2017,No,Twice,Fair
21609,15 February 2016,No,Twice,Fair
21610,14 June 2017,No,Twice,Fair
21611,15 January 2016,No,Twice,Fair
21612,14 October 2017,No,Twice,Fair

In [59]:
#Check Missing Values Again
df.isnull().sum()

ID                                           0
Date House was Sold                          0
Sale Price                                   0
No of Bedrooms                               0
No of Bathrooms                              0
Flat Area (in Sqft)                          0
Lot Area (in Sqft)                           0
No of Floors                                 0
Waterfront View                              0
No of Times Visited                          0
Condition of the House                       0
Overall Grade                                0
Area of the House from Basement (in Sqft)    0
Basement Area (in Sqft)                      0
Age of House (in Years)                      0
Renovated Year                               0
Zipcode                                      0
Latitude                                     0
Longitude                                    0
Living Area after Renovation (in Sqft)       0
Lot Area after Renovation (in Sqft)          0
dtype: int64

Scaling Numerical Variables
Identify all numerical columns (excluding the target variable SalePrice).
Scale these features using techniques like Min-Max scaling or Standard scaling.

In [60]:
#Scaling,Exclude Target Variable
features_to_scale = num_cols.drop("Sale Price")
df[features_to_scale]

,ID,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7.129301e+09,3.0,1.00,1180.0,5650.0,1.0,7.0,1180.0,0.0,63.0,0.0,98178.0,47.5112,-122.257,1340.0,5650.0
1,6.414100e+09,3.0,2.25,2570.0,7242.0,2.0,7.0,2170.0,400.0,67.0,1991.0,98125.0,47.7210,-122.319,1690.0,7639.0
2,5.631500e+09,2.0,1.00,770.0,10000.0,1.0,6.0,770.0,0.0,85.0,0.0,98028.0,47.7379,-122.233,2720.0,8062.0
3,2.487201e+09,4.0,3.00,1960.0,5000.0,1.0,7.0,1050.0,910.0,53.0,0.0,98136.0,47.5208,-122.393,1360.0,5000.0
4,1.954401e+09,3.0,2.00,1680.0,8080.0,1.0,8.0,1680.0,0.0,31.0,0.0,98074.0,47.6168,-122.045,1800.0,7503.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,2.630000e+08,3.0,2.50,1530.0,1131.0,3.0,8.0,1530.0,0.0,9.0,0.0,98103.0,47.6993,-122.346,1530.0,1509.0
21609,6.600060e+09,4.0,2.50,2310.0,5813.0,2.0,8.0,2310.0,0.0,4.0,0.0,98146.0,47.5107,-122.362,1830.0,7200.0
21610,1.523300e+09,2.0,0.75,1020.0,1350.0,2.0,7.0,1020.0,0.0,9.0,0.0,98144.0,47.5944,-122.299,1020.0,2007.0
21611,2.913101e+08,3.0,2.50,1600.0,2388.0,2.0,8.0,1600.0,0.0,14.0,0.0,98027.0,47.5345,-122.069,1410.0,1287.0
21612,1.523300e+09,2.0,0.75,1020.0,1076.0,2.0,7.0,1020.0,0.0,10.0,0.0,98144.0,47.5941,-122.299,1020.0,1357.0

In [61]:
#Create Scaler,Min-Max Scaler object create ചെയ്യുന്നു.
scaler = MinMaxScaler()

In [62]:
#Apply Scaling
df[features_to_scale] = scaler.fit_transform(df[features_to_scale])
df[features_to_scale]

,ID,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,0.720103,0.090909,0.12500,0.067170,0.003108,0.0,0.666667,0.097588,0.000000,0.521739,0.000000,0.893939,0.571498,0.217608,0.161934,0.005742
1,0.647853,0.090909,0.28125,0.172075,0.004072,0.4,0.666667,0.206140,0.082988,0.556522,0.988089,0.626263,0.908959,0.166113,0.222165,0.008027
2,0.568795,0.060606,0.12500,0.036226,0.005743,0.0,0.555556,0.052632,0.000000,0.713043,0.000000,0.136364,0.936143,0.237542,0.399415,0.008513
3,0.251157,0.121212,0.37500,0.126038,0.002714,0.0,0.666667,0.083333,0.188797,0.434783,0.000000,0.681818,0.586939,0.104651,0.165376,0.004996
4,0.197333,0.090909,0.25000,0.104906,0.004579,0.0,0.777778,0.152412,0.000000,0.243478,0.000000,0.368687,0.741354,0.393688,0.241094,0.007871
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,0.026467,0.090909,0.31250,0.093585,0.000370,0.8,0.777778,0.135965,0.000000,0.052174,0.000000,0.515152,0.874055,0.143688,0.194631,0.000986
21609,0.666639,0.121212,0.31250,0.152453,0.003206,0.4,0.777778,0.221491,0.000000,0.008696,0.000000,0.732323,0.570693,0.130399,0.246257,0.007523
21610,0.153783,0.060606,0.09375,0.055094,0.000503,0.4,0.666667,0.080044,0.000000,0.052174,0.000000,0.722222,0.705324,0.182724,0.106866,0.001558
21611,0.029327,0.090909,0.31250,0.098868,0.001132,0.4,0.777778,0.143640,0.000000,0.095652,0.000000,0.131313,0.608975,0.373754,0.173980,0.000731
21612,0.153783,0.060606,0.09375,0.055094,0.000337,0.4,0.666667,0.080044,0.000000,0.060870,0.000000,0.722222,0.704842,0.182724,0.106866,0.000811

Encoding Categorical Variables
Identify all categorical columns in the dataset.
Apply appropriate encoding techniques:
Use One-Hot Encoding for nominal categories.
Use Label Encoding for ordinal categories, if applicable.

In [63]:
#Encoding
# Re-identify categorical columns to ensure we're working with current columns
cat_cols = df.select_dtypes(include=['object']).columns
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

In [65]:
#Outlier Removal
numeric_columns = df.select_dtypes(include=np.number).columns
numeric_columns = numeric_columns.drop("Sale Price")


#SalePrice ഒഴിവാക്കി എല്ലാ numerical columns select ചെയ്യുന്നു.

In [66]:
for col in numeric_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df = df[(df[col] >= lower) & (df[col] <= upper)]

Train-Test Split
Set aside the SalePrice column as the target variable.
Split the dataset into training (80%) and testing (20%) sets using the train_test_split function from sklearn

In [68]:
#train-Test Split
# Features and Target
X = df.drop("Sale Price", axis=1)

y = df["Sale Price"]

In [69]:
#Split Dataset
x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [71]:
#Check Shape
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(12082, 36)
(3021, 36)
(12082,)
(3021,)

CASE STUDY COMPLETEED