<a href="https://colab.research.google.com/github/sreejas7919-bit/DSA_6/blob/main/pandas_activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
PANDAS ACTIVITY

QUESTION 1

1. Load the Titanic dataset and display the first 10 rows.

SOLUTION 1

| Function              | Purpose                                     |
| --------------------- | ------------------------------------------- |
| `import pandas as pd` | Imports the Pandas library                  |
| `pd.read_csv()`       | Loads the CSV file into a DataFrame         |
| `df.head(10)`         | Displays the first 10 rows of the DataFrame |
| `print()`             | Displays the output                         |

In [5]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/titanic_dataset (1).csv')
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

QUESTION 2
Find the number of missing values in each column.

| Function        | Purpose                                            |
| --------------- | -------------------------------------------------- |
| `pd.read_csv()` | Loads the CSV file into a DataFrame                |
| `df.isnull()`   | Identifies missing (null) values                   |
| `.sum()`        | Counts the number of missing values in each column |
| `print()`       | Displays the output                                |

In [6]:
missing_values = df.isnull().sum()
print(missing_values)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

QUESTION 3
Find the percentage of passengers who survived, grouped by gender.

In [7]:
df.groupby('Sex')['Survived'].mean() * 100

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

QUESTION 4
Find the average, median, and standard deviation of passenger ages.

In [8]:
average_age = df['Age'].mean()
median_age = df['Age'].median()
std_dev_age = df['Age'].std()
print("Average Age:", average_age)
print("Median Age:", median_age)
print("Standard Deviation of Age:", std_dev_age)

Average Age: 29.69911764705882
Median Age: 28.0
Standard Deviation of Age: 14.526497332334044

question 5
Count how many passengers were in each class (pclass).

In [ ]:
class_counts = df['Pclass'].value_counts()
print(class_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

question 6
Show all passengers who were female, under age 18, and survived.

In [9]:
result = df[(df['Sex'] == 'female') &
            (df['Age'] < 18) &
            (df['Survived'] == 1)]

print(result)

     PassengerId  Survived  Pclass  \
9             10         1       2
10            11         1       3
22            23         1       3
39            40         1       3
43            44         1       2
58            59         1       2
68            69         1       3
84            85         1       2
156          157         1       3
172          173         1       3
184          185         1       3
208          209         1       3
233          234         1       3
237          238         1       2
307          308         1       1
329          330         1       1
381          382         1       3
389          390         1       2
435          436         1       1
446          447         1       2
448          449         1       3
469          470         1       3
479          480         1       3
504          505         1       1
530          531         1       2
535          536         1       2
618          619         1       2
644          645         1       3
689          690         1       1
691          692         1       3
720          721         1       2
750          751         1       2
777          778         1       3
780          781         1       3
781          782         1       1
830          831         1       3
853          854         1       1
875          876         1       3

                                                  Name     Sex    Age  SibSp  \
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.00      1
10                     Sandstrom, Miss. Marguerite Rut  female   4.00      1
22                         McGowan, Miss. Anna "Annie"  female  15.00      0
39                         Nicola-Yarred, Miss. Jamila  female  14.00      1
43            Laroche, Miss. Simonne Marie Anne Andree  female   3.00      1
58                        West, Miss. Constance Mirium  female   5.00      1
68                     Andersson, Miss. Erna Alexandra  female  17.00      4
84                                 Ilett, Miss. Bertha  female  17.00      0
156                   Gilnagh, Miss. Katherine "Katie"  female  16.00      0
172                       Johnson, Miss. Eleanor Ileen  female   1.00      1
184                Kink-Heilmann, Miss. Luise Gretchen  female   4.00      0
208                          Carr, Miss. Helen "Ellen"  female  16.00      0
233                     Asplund, Miss. Lillian Gertrud  female   5.00      4
237                   Collyer, Miss. Marjorie "Lottie"  female   8.00      0
307  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.00      1
329                       Hippach, Miss. Jean Gertrude  female  16.00      0
381                        Nakid, Miss. Maria ("Mary")  female   1.00      0
389                              Lehmann, Miss. Bertha  female  17.00      0
435                          Carter, Miss. Lucile Polk  female  14.00      1
446                  Mellinger, Miss. Madeleine Violet  female  13.00      0
448                     Baclini, Miss. Marie Catherine  female   5.00      2
469                      Baclini, Miss. Helene Barbara  female   0.75      2
479                           Hirvonen, Miss. Hildur E  female   2.00      0
504                              Maioni, Miss. Roberta  female  16.00      0
530                           Quick, Miss. Phyllis May  female   2.00      1
535                             Hart, Miss. Eva Miriam  female   7.00      0
618                        Becker, Miss. Marion Louise  female   4.00      2
644                             Baclini, Miss. Eugenie  female   0.75      2
689                  Madill, Miss. Georgette Alexandra  female  15.00      0
691                                 Karun, Miss. Manca  female   4.00      0
720                  Harper, Miss. Annie Jessie "Nina"  female   6.00      0
750                                  Wells, Miss. Joan  female   4.00      1
777                      Emanuel, Miss. Virginia Ethel  female   5.00      0
780                               Ayoub, Miss. Banoura  female  13.00      0
781          Dick, Mrs. Albert Adrian (Vera Gillespie)  female  17.00      1
830            Yasbeck, Mrs. Antoni (Selini Alexander)  female  15.00      1
853                          Lines, Miss. Mary Conover  female  16.00      0
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.00      0

     Parch         Ticket      Fare    Cabin Embarked
9        0         237736   30.0708      NaN        C
10       1        PP 9549   16.7000       G6        S
22       0         330923    8.0292      NaN        Q
39       0           2651   11.2417      NaN        C
43       2  SC/Paris 2123   41.5792      NaN        C
58       2     C.A. 34651   27.7500      NaN        S
68       2        3101281    7.9250      NaN        S
84       0     SO/C 14885   10.5000      NaN        S
156      0          35851    7.7333      NaN        Q
172      1         347742   11.1333      NaN        S
184      2         315153   22.0250      NaN        S
208      0         367231    7.7500      NaN        Q
233      2         347077   31.3875      NaN        S
237      2     C.A. 31921   26.2500      NaN        S
307      0       PC 17758  108.9000      C65        C
329      1         111361   57.9792      B18        C
381      2           2653   15.7417      NaN        C
389      0        SC 1748   12.0000      NaN        C
435      2         113760  120.0000  B96 B98        S
446      1         250644   19.5000      NaN        S
448      1           2666   19.2583      NaN        C
469      1           2666   19.2583      NaN        C
479      1        3101298   12.2875      NaN        S
504      0         110152   86.5000      B79        S
530      1          26360   26.0000      NaN        S
535      2   F.C.C. 13529   26.2500      NaN        S
618      1         230136   39.0000       F4        S
644      1           2666   19.2583      NaN        C
689      1          24160  211.3375       B5        S
691      1         349256   13.4167      NaN        C
720      1         248727   33.0000      NaN        S
750      1          29103   23.0000      NaN        S
777      0         364516   12.4750      NaN        S
780      0           2687    7.2292      NaN        C
781      0          17474   57.0000      B20        S
830      0           2659   14.4542      NaN        C
853      1       PC 17592   39.4000      D28        S
875      0           2667    7.2250      NaN        C

q 7
Replace missing age values with the median age.

In [10]:
median_age = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age)
print(df['Age'])

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

Q8 . Create a column age_group with values:
a. 'Child' for age < 18
b. 'Adult' for age 18–60
c. 'Senior' for age > 60
d. Use: apply() or np.where() or custom function

In [11]:
def age_group(age):
    if age < 18:
        return 'Child'
    elif age <= 60:
        return 'Adult'
    else:
        return 'Senior'

df['age_group'] = df['Age'].apply(age_group)

df[['Age','age_group']].head()

    Age age_group
0  22.0     Adult
1  38.0     Adult
2  26.0     Adult
3  35.0     Adult
4  35.0     Adult

Q9
Display the top 5 passengers who paid the highest fare.

In [12]:
df.sort_values(by='Fare', ascending=False).head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_group
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,Adult
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,Adult
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,Adult
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,Adult
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,Senior

Q10
 Find the average fare paid, grouped by both pclass and sex.

In [13]:
avg_fare = df.groupby(['Pclass', 'Sex'])['Fare'].mean()
print(avg_fare)

Pclass  Sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

Q11
Rename the following columns:



sex → gender


fare → ticket_fare

In [16]:
df.rename(columns={
    'Sex':'gender',
    'Fare':'ticket_fare'
}, inplace=True)

df.head()

,PassengerId,Survived,Pclass,Name,gender,Age,SibSp,Parch,Ticket,ticket_fare,Cabin,Embarked,age_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult

Question 12

Count the number of passengers who survived and didn’t survive, grouped by class

In [17]:

result = df.groupby('Pclass')['Survived'].value_counts()

print(result)

Pclass  Survived
1       1           136
        0            80
2       0            97
        1            87
3       0           372
        1           119
Name: count, dtype: int64

Question 13

Find the average age of passengers grouped by both class and gender.

In [19]:

avg_age = df.groupby(['Pclass', 'gender'])['Age'].mean()

print(avg_age)

Pclass  gender
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: Age, dtype: float64

**PANDAS ACTIVITY COMPLETED**